// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPC-AbGI-PNPjJnRwKJwmRtMPqxoVo8Q',
    appId: '1:672085163734:web:68aa4ece8a658e75c41377',
    messagingSenderId: '672085163734',
    projectId: 'flutter-todo-test-project',
    authDomain: 'flutter-todo-test-project.firebaseapp.com',
    databaseURL: 'https://flutter-todo-test-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-todo-test-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdO_PCNSIDadvcFacPzLIGeSp9Qic2fM',
    appId: '1:672085163734:android:584b966e40dad2a2c41377',
    messagingSenderId: '672085163734',
    projectId: 'flutter-todo-test-project',
    databaseURL: 'https://flutter-todo-test-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-todo-test-project.firebasestorage.app',
  );

}